version: '3.8'

services:
  app:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: cloud_app
    ports:
      - "8000:8000"   # Laravel
      - "5174:5174"   # Vite Dev Server
    volumes:
      - ./src:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/conf.d/uploads.ini  # ⬅️ php.ini mount di sini
    depends_on:
      - mysql
      - minio
    command: sh -c "npm run dev -- --port 5174 --host & php artisan serve --host=0.0.0.0 --port=8000"

  mysql:
    image: mysql:8
    container_name: cloud_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cloud_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  minio:
    image: minio/minio
    container_name: cloud_minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - ./minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"

volumes:
  mysql_data:
